spring:
  application:
    name: ares
  cloud:
    gcp:
      sql:
        enabled: false
      core:
        enabled: false
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

ares:
  mcp:
    providers:
      notion:
        enabled: true
        server-url: "https://mcp.notion.com/mcp"
        auth-token: ${NOTION_MCP_TOKEN:}
        server-command: "npx"
        args: [ "-y", "@notionhq/notion-mcp-server" ]
      github:
        enabled: true
        server-url: "https://api.githubcopilot.com/mcp/"
        auth-token: ${GITHUB_MCP_TOKEN:}
