spring:
  application:
    name: ares
  cloud:
    gcp:
      sql:
        enabled: false
        database-name: "unused"
        instance-connection-name: "none:none"
  threads:
    virtual:
      enabled: true

ares:
  mcp:
    providers:
      notion:
        enabled: true
        server-url: "https://mcp.notion.com/mcp"
        auth-token: ${NOTION_MCP_TOKEN:}
        server-command: "npx"
        args: [ "-y", "@notionhq/notion-mcp-server" ]
      github:
        enabled: true
        server-url: "https://api.githubcopilot.com/mcp/"
        auth-token: ${GITHUB_MCP_TOKEN:}
